<?php

declare(strict_types=1);

namespace DDD\Domain\Common\Entities\MediaItems;

use DDD\Infrastructure\Base\DateTime\DateTime;
use DDD\Infrastructure\Exceptions\InternalErrorException;
use DDD\Infrastructure\Validation\Constraints\Choice;
use Exception;
use PhpOffice\PhpSpreadsheet\Cell\Coordinate;
use PhpOffice\PhpSpreadsheet\Shared\Date as ExcelDate;
use PhpOffice\PhpSpreadsheet\Spreadsheet;
use PhpOffice\PhpSpreadsheet\Style\Alignment;
use PhpOffice\PhpSpreadsheet\Writer\Xlsx;

class ExcelDocument extends Document
{
    /** @var string|null The type of the mediaitem */
    #[Choice(choices: [self::TYPE_PHOTO, self::TYPE_VIDEO, self::TYPE_DOCUMENT])]
    public ?string $type = self::TYPE_DOCUMENT;

    /** @var string The title of the Excel document */
    public ?string $title;

    /** @var string|null The Author's name */
    public ?string $author = null;

    /** @var GenericMediaItemContent Excel File Content */
    public GenericMediaItemContent $mediaItemContent;

    /** @var Spreadsheet|null The loaded spreadsheet object */
    protected ?Spreadsheet $spreadsheet = null;

    public const array INVALID_CHARACTERS = ['*', ':', '/', '\\', '?', '[', ']'];

    public function __construct(
        ?string $title = null,
        ?string $author = null,
        ?DateTime $createdDateTime = null,
        ?DateTime $modifiedDateTime = null
    ) {
        $this->title = $title;
        $this->author = $author;
        $this->createdDateTime = $createdDateTime ?? new DateTime();
        $this->modifiedDateTime = $modifiedDateTime ?? new DateTime();
        parent::__construct();
    }

    public function getSpreadsheet(): ?Spreadsheet
    {
        if (!isset($this->spreadsheet)) {
            $this->spreadsheet = new Spreadsheet();
            $this->spreadsheet->removeSheetByIndex(0);
            $title = isset($this->title) ? $this->title : null;
            $author = isset($this->author) ? $this->author : null;
            $this->spreadsheet->getProperties()->setCreator($author ?? 'DDD Framework')->setLastModifiedBy($author ?? 'DDD Framework')->setTitle(
                $title ?? 'Excel Document'
            )->setSubject($title ?? 'Excel Document')->setDescription('Document generated by DDD Framework');
            if (isset($this->createdDateTime)) {
                $this->spreadsheet->getProperties()->setCreated($this->createdDateTime->getTimestamp());
            }

            if (isset($this->modifiedDateTime)) {
                $this->spreadsheet->getProperties()->setModified($this->modifiedDateTime->getTimestamp());
            }
        }
        return $this->spreadsheet;
    }

    /**
     * Converts the first sheet of the Excel document to HTML
     *
     * @return string HTML representation of the Excel document
     * @throws InternalErrorException
     */
    public function toHTML(): string
    {
        try {
            $spreadsheet = $this->getSpreadsheet();
            $sheet = $spreadsheet->getActiveSheet();

            $html = '<table border="1" cellpadding="5" cellspacing="0">';

            // Get the highest row and column indexes
            $highestRow = $sheet->getHighestRow();
            $highestColumn = $sheet->getHighestColumn();

            // Loop through each row
            for ($row = 1; $row <= $highestRow; $row++) {
                $html .= '<tr>';

                // Loop through each column in the row
                for ($col = 'A'; $col <= $highestColumn; $col++) {
                    $cellValue = $sheet->getCell($col . $row)->getValue();
                    $html .= '<td>' . htmlspecialchars((string)$cellValue) . '</td>';
                }

                $html .= '</tr>';
            }

            $html .= '</table>';

            return $html;
        } catch (Exception $e) {
            throw new InternalErrorException('Error converting Excel to HTML: ' . $e->getMessage());
        }
    }

    /**
     * Creates and populates a sheet from a data array
     *
     * @param Spreadsheet $spreadsheet
     * @param string $sheetTitle
     * @param array $data
     * @param array|null $headers
     * @param int $startRow
     */
    protected static function createSheetFromArray(
        Spreadsheet $spreadsheet,
        string $sheetTitle,
        array $data,
        ?array $headers = null,
        int $startRow = 1
    ): void {
        $sheet = $spreadsheet->createSheet();
        $sheet->setTitle(self::cleanSheetTitle($sheetTitle));

        if ($headers) {
            $sheet->fromArray($headers, null, 'A1');
            $lastColumn = Coordinate::stringFromColumnIndex(count($headers));
            $sheet->getStyle('A1:' . $lastColumn . '1')->applyFromArray([
                'font' => ['bold' => true],
            ]);
            $startRow = 2;
        }

        foreach ($data as $rowIndex => $row) {
            foreach ($row as $colIndex => $value) {
                $cellCoordinate = Coordinate::stringFromColumnIndex($colIndex + 1) . ($rowIndex + $startRow);
                if ($value instanceof \DateTime) {
                    $sheet->setCellValue($cellCoordinate, ExcelDate::PHPToExcel($value));
                    $sheet->getStyle($cellCoordinate)->getNumberFormat()->setFormatCode('yyyy-mm-dd hh:mm:ss');
                } else {
                    $sheet->setCellValue($cellCoordinate, $value);
                    if (is_string($value) && strpos($value, "\n") !== false) {
                        $sheet->getStyle($cellCoordinate)->getAlignment()->setWrapText(true)->setVertical(Alignment::VERTICAL_TOP);
                    }
                }
            }
        }

        foreach ($sheet->getColumnIterator() as $column) {
            $sheet->getColumnDimension($column->getColumnIndex())->setAutoSize(true);
        }
    }

    /**
     * Adds a new sheet to the Excel document from a data array.
     *
     * @param string $sheetTitle Title of the new sheet
     * @param array $data Data to populate the sheet (2D array of rows and columns)
     * @param array|null $headers Optional header row to prepend to the data
     * @return ExcelDocument Returns the current ExcelDocument instance for chaining
     */
    public function addSheetFromData(string $sheetTitle, array $data, array $headers = null): ExcelDocument
    {
        $spreadsheet = $this->getSpreadsheet();
        self::createSheetFromArray($spreadsheet, self::cleanSheetTitle($sheetTitle), $data, $headers);

        // Update the binary content after modifying the spreadsheet
        $writer = new Xlsx($spreadsheet);
        ob_start();
        $writer->save('php://output');
        $this->mediaItemContent->body = ob_get_clean();
        return $this;
    }

    public static function cleanSheetTitle(string $title): string
    {
        return str_replace(self::INVALID_CHARACTERS, '', $title);
    }

    /**
     * Creates an Excel document from a single data array
     *
     * @param array $data Two-dimensional array of data (rows and columns)
     * @param array|null $headers Optional headers for the columns
     * @param string|null $title Optional title for the document
     * @param string|null $author Optional author name
     * @param string|null $sheetName Optional sheet name
     * @param DateTime|null $createdDateTime Optional creation date
     * @param DateTime|null $modifiedDateTime Optional modification date
     * @return ExcelDocument
     */
    public static function fromArray(
        array $data,
        ?array $headers = null,
        ?string $title = null,
        ?string $author = null,
        ?string $sheetName = null,
        ?DateTime $createdDateTime = null,
        ?DateTime $modifiedDateTime = null,
    ): ExcelDocument {
        $spreadsheet = new Spreadsheet();
        $spreadsheet->removeSheetByIndex(0); // Remove default sheet
        if (!$sheetName) {
            $sheetName = $title ?? 'Sheet 1';
        }

        self::createSheetFromArray($spreadsheet, $sheetName, $data, $headers);

        $excelDocument = new static($title, $author, $createdDateTime, $modifiedDateTime);
        $spreadsheet = $excelDocument->getSpreadsheet();
        $excelDocument->addSheetFromData($sheetName, $data, $headers);

        $excelDocument->mediaItemContent = new GenericMediaItemContent();
        $excelDocument->addChildren($excelDocument->mediaItemContent);

        $writer = new Xlsx($spreadsheet);
        ob_start();
        $writer->save('php://output');
        $excelDocument->mediaItemContent->body = ob_get_clean();

        return $excelDocument;
    }

    /**
     * Creates an Excel document from a PhpSpreadsheet object
     *
     * @param Spreadsheet $spreadsheet The spreadsheet object
     * @param string|null $title Optional title for the document
     * @param DateTime|null $createdDateTime Optional creation date
     * @param DateTime|null $modifiedDateTime Optional modification date
     * @return ExcelDocument
     */
    public static function fromSpreadsheet(
        Spreadsheet $spreadsheet,
        ?string $title = null,
        ?DateTime $createdDateTime = null,
        ?DateTime $modifiedDateTime = null
    ): ExcelDocument {
        $excelDocument = new static($title, null, $createdDateTime, $modifiedDateTime);
        $excelDocument->mediaItemContent = new GenericMediaItemContent();
        $excelDocument->addChildren($excelDocument->mediaItemContent);
        $excelDocument->spreadsheet = $spreadsheet;
        // Write to memory
        $writer = new Xlsx($spreadsheet);
        ob_start();
        $writer->save('php://output');
        $excelDocument->mediaItemContent->body = ob_get_clean();

        return $excelDocument;
    }

    /**
     * Gets the filename for the Excel document
     *
     * @return string|null The filename
     */
    public function getFileName(): ?string
    {
        $fileName = null;

        if (isset($this->fileName)) {
            $fileName = $this->fileName;
        } elseif (isset($this->title)) {
            $fileName = $this->title;
        }

        // Check if the fileName is set and does not end with '.xlsx'
        if ($fileName !== null && substr($fileName, -5) !== '.xlsx') {
            $fileName .= '.xlsx'; // Add '.xlsx' to the end
        }

        return $fileName;
    }

    /**
     * Forces download of the Excel document
     */
    public function download(): void
    {
        // Set headers to force download
        header('Content-Type: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');
        header('Content-Disposition: attachment; filename="' . $this->getFileName() . '"');
        header('Content-Length: ' . strlen($this->mediaItemContent->body));
        header('Cache-Control: max-age=0');

        // Output the Excel content
        echo $this->mediaItemContent->body;
        exit;
    }

    /**
     * Extracts text content from all sheets in the Excel document
     *
     * @return string The extracted text
     * @throws InternalErrorException
     */
    public function getTextContent(): string
    {
        try {
            $spreadsheet = $this->getSpreadsheet();
            $textContent = '';

            foreach ($spreadsheet->getAllSheets() as $sheet) {
                $textContent .= $sheet->getTitle() . ":\n\n";

                // Get the highest row and column indexes
                $highestRow = $sheet->getHighestRow();
                $highestColumn = $sheet->getHighestColumn();

                // Loop through each row
                for ($row = 1; $row <= $highestRow; $row++) {
                    $rowData = [];

                    // Loop through each column in the row
                    for ($col = 'A'; $col <= $highestColumn; $col++) {
                        $cellValue = $sheet->getCell($col . $row)->getValue();
                        if ($cellValue !== null && $cellValue !== '') {
                            $rowData[] = $cellValue;
                        }
                    }

                    if (!empty($rowData)) {
                        $textContent .= implode("\t", $rowData) . "\n";
                    }
                }

                $textContent .= "\n\n";
            }

            return $textContent;
        } catch (Exception $e) {
            throw new InternalErrorException('Error extracting text from Excel: ' . $e->getMessage());
        }
    }
}